# Iniciando
Curso: Aplicaciones de Machine Learning <br>
Actividad 1: Iniciando con Python.

Objetivos:
1. Familiarizarse con el lenguaje de programación Python.
2. Hacer llamadas a funciones.
3. Conocer la estructura de datos listas
4. Conocer la biblioteca numpy.
5. Conocer la biblioteca matplotlib.

Dra. Jessica Beltrán Márquez <br>
jessicabeltran.net

A continuación asignaremos valores a dos variables y después las sumaremos. Python es sensible a mayúsculas y minúsculas, por lo que la variable "a" es distinta que "A".

In [ ]:
a = 5
b = 7
A = 25

c = a + b
d = A + b

print("a + b = ", c)
print("A + b = ", d)


Intenta cambiar los valores de las variables y prueba los distintos resultados.

### Llamadas a funciones

A continuación usaremos funciones definidas en la biblioteca math. Para esto primero debemos importar la biblioteca utilizando *import math*

In [2]:
import math #Aqui se importa la biblioteca math
a = math.factorial(3)   #Se utiliza la función factorial definida dentro de la biblioteca math.
b = math.sqrt(4)        #Se utiliza la función sqrt definida dentro de la biblioteca math.
c = math.ceil(4.12)     #Se utiliza la función ceil definida dentro de la biblioteca math.

print("Factorial de 3 =", a)
print("La raíz cuadrada de 4 =", b)
print("El techo de 4.12 =", c)

Factorial de 3 = 6
La raíz cuadrada de 4 = 2.0
El techo de 4.12 = 5


### Listas
Las listas es una estructura de datps en Python que nos permite tener una colección ordenada de elementos, es decir, nos permite almacenar secuencias de *items* en una lista.

Los *items* deben definirse dentro de corchetes. Una vez definida una lista, es posible agregar, eliminar y buscar *items* en la lista.

In [3]:
#Ejemplo de una lista
l = [1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [4]:
#Ejemplo de una lista con números y caracteres
l2 = [5,8,"a"]
print(l2)

[5, 8, 'a']


Para acceder a los elementos de la lista, se utiliza un índice. El primer índice de la lista es el 0. 

In [5]:
#Para acceder a un elemento
print(l[0])

1


Se pueden acceder a varios elementos de una lista al mismo tiempo. 

In [6]:
print(l2[0:2])  #En este caso se accede desde el elemento 0 hasta el 2 (sin incluir el 2)

[5, 8]


In [7]:
listaCompras = ["manzanas","mango","zanahorias","platano"]
print(listaCompras[1:3])   #Se accede desde el índice 1 hasta el 3 (sin incluir el 3)

['mango', 'zanahorias']


Las estructura de datos *listas* permiten otras operaciones 

In [8]:
listaCompras.append("jugo")   #Agregar elementos
print(listaCompras)

['manzanas', 'mango', 'zanahorias', 'platano', 'jugo']


In [9]:
listaCompras.sort()
print(listaCompras)

['jugo', 'mango', 'manzanas', 'platano', 'zanahorias']


Aunque las listas son útiles en varias aplicaciones. No proveen la ventaja de poder realizar operaciones matemáticas.  Por ejemplo, si se quisiera obtener la raíz cuadrada de todos los elementos de la lista Python regresa un error. Por este motivo se utiliza la biblioteca *numpy*.

In [10]:
a = [1,2,3]
c = math.sqrt(a)
print(a)

TypeError: a float is required

## Numpy
A continuación usaremos la biblioteca numpy y realizaremos operaciones matemáticas con los arreglos y matrices que definamos.

In [11]:
import numpy as np   #Se importa la biblioteca numpy como np, así para llamar sus funciones solo escribimos np en vez de numpy.
a = np.array([1,2,3,4])   #Se declara un arreglo
print(a)
b = np.sqrt(a)            #Se obtiene la raíz cuadrada para cada elemento del arreglo a
print(b)

[1 2 3 4]
[ 1.          1.41421356  1.73205081  2.        ]


El arreglo a = np.array([1,2,3,4])  --> [1 2 3 4]   es un arreglo de *rank* 1 ya que tiene solo un eje. Ese eje tiene una longitud de 4 elementos.

En el ejemplo a continuación, el arreglo tiene un *rank* 2 (es bidimensional). El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.  Es un arreglo de forma (shape) 2x3.

In [12]:
a = np.array([[1.0, 0.0, 0.01],[1.1, 0, 2]])
print(a)

[[ 1.    0.    0.01]
 [ 1.1   0.    2.  ]]


In [13]:
#Para acceder a la forma del array se utiliza la función shape
print(a.shape)

(2, 3)


Existen funciones que crean arreglos especiales. Por ejemplo *zeros* que crea arreglos con 0's o *ones* que crea arreglos con 1's.

In [14]:
a = np.zeros([2,3])
print(a)
b = np.ones([2,4,6])
print(b)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]]


Para acceder a elementos especificos de los arreglos se utilizan índices.

In [15]:
a[1,1]=2
print(a)

[[ 0.  0.  0.]
 [ 0.  2.  0.]]


In [16]:
b[:,1:3,1:5] = 2
print(b)

[[[ 1.  1.  1.  1.  1.  1.]
  [ 1.  2.  2.  2.  2.  1.]
  [ 1.  2.  2.  2.  2.  1.]
  [ 1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  2.  2.  2.  2.  1.]
  [ 1.  2.  2.  2.  2.  1.]
  [ 1.  1.  1.  1.  1.  1.]]]


### Matplotlib
La biblioteca Matplotlib nos permite producir figuras en 2D.

In [1]:
import matplotlib.pyplot as plt
from numpy import pi   # Se importa pi de numpy para usarlo directamente

x = np.linspace(0,2*pi,100)         #La función linspace nos generará 100 números del 0 a 2*pi
y = np.sin(x)
plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.show()

ImportError: No module named 'matplotlib'